# Generated by Django 3.1.6 on 2021-05-31 02:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.gen_unique_code, max_length=8, unique=True),
        ),
    ]
