# Generated by Django 3.1.6 on 2021-06-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210530_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='votes_to_skip',
        ),
    ]
